version: '3.7'

services:
  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    image: cake
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - mysql
    volumes:
      - '.:/var/www'
    networks:
      - cake

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - cake

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
    ports:
      - 33060:3306
    networks:
      - cake

networks:
  cake:
    driver: bridge

